services:
  translator:
    image: username/translator:latest   # 修改為您的映像地址
    container_name: translator
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7861
      - GRADIO_ROOT_PATH=/translator    # 可根據您的部署路徑調整
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://ollama:11434  # 修改為您的 Ollama 服務地址
    volumes:
      - ~/docker/translator/log:/app/log        # 修改為您的本地路徑
      - ~/docker/translator/outputs:/app/outputs  # 修改為您的本地路徑
      - ~/docker/translator/cache:/root/.cache    # 修改為您的本地路徑
    # 如果使用 Traefik，請取消以下注釋並調整值
    labels:
      - traefik.enable=true
      - traefik.http.routers.translator.rule=PathPrefix(`/translator`)
      - traefik.http.routers.translator.entrypoints=websecure
      - traefik.http.routers.translator.tls=true
      - traefik.http.routers.translator.tls.certresolver=myresolver
      - traefik.http.routers.translator.service=translator
      - traefik.http.services.translator.loadbalancer.server.port=7861
    networks:
      - traefik

# 如果使用 Traefik，取消以下注釋
networks:
  traefik:
    external: true
