services:
  translator:
    image: username/translator:latest   # Change to your image address
    container_name: translator
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7861
      - GRADIO_ROOT_PATH=/translator    # Adjust according to your deployment path
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://ollama:11434  # Change to your Ollama service address
    volumes:
      - ~/docker/translator/log:/app/log        # Change to your local path
      - ~/docker/translator/outputs:/app/outputs  # Change to your local path
      - ~/docker/translator/cache:/root/.cache    # Change to your local path
    # If using Traefik, uncomment below and adjust values
    labels:
      - traefik.enable=true
      - traefik.http.routers.translator.rule=PathPrefix(`/translator`)
      - traefik.http.routers.translator.entrypoints=websecure
      - traefik.http.routers.translator.tls=true
      - traefik.http.routers.translator.tls.certresolver=myresolver
      - traefik.http.routers.translator.service=translator
      - traefik.http.services.translator.loadbalancer.server.port=7861
    networks:
      - traefik

# If using Traefik, uncomment below
networks:
  traefik:
    external: true
